name: Build Garland

on: [push, pull_request]

jobs:
  build:
    name: Build .NET assemblies
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    steps:
    - name: Check out repo
      uses: actions/checkout@v3
    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'
    - name: Build solution
      run: dotnet publish Garland.sln -c Release -o output
    - name: Move output
      run: mkdir -p artifacts/{client,server} && rsync client/assets/ artifacts/client && rsync server/assets/ artifacts/server && mkdir artifacts/client/plugins && mv output/Client.dll artifacts/client/plugins/Client.dll && mkdir artifacts/server/plugins && mv output/Server.dll artifacts/server/plugins/Server.dll
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        path: |
          artifacts/client
          artifacts/server
    - name: Upload release
      if: startsWith(github.ref, 'refs/tags/0.' )
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        prerelease: true
        files: |
          artifacts/client
          artifacts/server
