name: Build

on: [push]

jobs:
  build:
    name: Build .NET assemblies
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    steps:
    - name: Check out repo
      uses: actions/checkout@v3
    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'
    - name: Run sourcegen
      run: cd sourcegen && dotnet run
    - name: Build solution
      run: dotnet publish -c Release -o output
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        path: |
          output/Client.dll
          output/Server.dll
    - name: Upload release
      if: startsWith(github.ref, 'refs/tags/0.' )
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        prerelease: true
        files: |
          output/Client.dll
          output/Server.dll
